options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '*.py',  'gs://us-central1-airbnb-composer-992ece21-bucket/dags/']

